// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csqwejgnevzlyljtzbkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzcXdlamduZXZ6bHlsanR6Ymt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0ODg1NDIsImV4cCI6MjA1MTA2NDU0Mn0.fMn_O5a-9PsD6ZqCuPBjqoLwAudbAlOBkoinR7BIK8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);